export default {
  'menu.admin.sysDataRule': '数据规则管理',
  // form
  'admin.data-rule.form.name': '名称',
  'admin.data-rule.form.search': '搜索',
  'admin.data-rule.form.reset': '重置',
  'admin.data-rule.form.name.help': '规则名称是必填项',
  'admin.data-rule.form.model.help': '规则模型是必填项',
  'admin.data-rule.form.column.help': '规则模型列是必填项',
  'admin.data-rule.form.value.help': '规则值是必填项',
  // placeholder
  'admin.data-rule.form.name.placeholder': '请输入数据规则名称',
  'admin.data-rule.form.model.placeholder': '请选择数据规则模型',
  'admin.data-rule.form.column.placeholder': '请选择数据规则模型列',
  'admin.data-rule.form.value.placeholder': '请输入数据规则值',
  // button
  'admin.data-rule.button.create': '新增',
  'admin.data-rule.button.delete': '删除',
  // columns
  'admin.data-rule.columns.name': '名称',
  'admin.data-rule.columns.model': '模型',
  'admin.data-rule.columns.column': '模型列',
  'admin.data-rule.columns.operator': '运算符',
  'admin.data-rule.columns.expression': '表达式',
  'admin.data-rule.columns.value': '规则值',
  'admin.data-rule.columns.operate': '操作',
  'admin.data-rule.columns.edit': '编辑',
  // drawer
  'admin.data-rule.columns.new.drawer': '新增数据规则',
  'admin.data-rule.columns.edit.drawer': '更新数据规则',
  'admin.data-rule.columns.delete.drawer': '删除数据规则',
};
